### ISSUE TITLE
Fitness model

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#10]
I'd propose to implement a fitness model along the lines of L&L 2014 eq 20 where the fitness of virus _i_ in season _j_ is a linear combination of a set of continuous predictors:

![image](https://cloud.githubusercontent.com/assets/1176109/5944718/fb668210-a6dd-11e4-8d0a-150019bad7b6.png)

Here _f<sub>i,j</sub><sup>ep</sup>_ derives from epitope distance of virus _i_ following:

![image](https://cloud.githubusercontent.com/assets/1176109/5944694/c05d8164-a6dd-11e4-9c7c-22ae41ffde9e.png)

where _&mu;<sub>j</sub><sup>ep</sup>_ is the mean epitope distance across viruses isolated in season _j_ and _&sigma;<sup>ep</sup>_ is the standard deviation of epitope distance of circulating viruses averaged across seasons. This way _f<sub>i,j</sub><sup>ep</sup>_ is zero-centered, but its variance can differ across seasons (but the variance averaged over seasons is still 1).

This makes it so that _&beta;<sup>ep</sup>_, _&beta;<sup>ne</sup>_ and _&beta;<sup>lb</sup>_ can be directly compared in terms of their influence on overall fitness.

A number of predictors could be included in such a model. In each case the associated _&beta;_ would be estimated in a machine learning fashion based on minimizing prediction error of clade frequencies between season _j_ and season _j_+1.

**Comment by rneher** [comment]
makes sense to me. I am interested to see it at work! 

on a different note: what about adding HI antigen dimension 1 to the tree?

**Comment by rneher** [comment]
I just pushed a rough scaffold outlining a possible structure of a fitness model. but I will call it a day now.

**Comment by trvrb** [comment]
Wonderful! However, although I see a [`fitness_model`](https://github.com/blab/nextflu/tree/fitness_model) branch. I don't see any new commits attached to it.

**Comment by rneher** [comment]
I pulled instead of pushed. now it hsould be there

**Comment by trvrb** [comment]
Got it. Thanks.

**Comment by trvrb** [comment]
I was just thinking more about this and I'm now not sure how `make_flat_lists_per_season` is actually going to work. The issue is that to predict a clade's frequency in season _j_ + 1, you need to know all the frequencies of all living viruses that subtend this clade. This is eq 1 in L&L (2014). I would think you need to the keep the tree to efficiently parse this out.

**Comment by rneher** [comment]
Yes, you need the tree. but only once. Once you have built the list, you can use it in every iteration of the optimization, right?
I was also thinking a little more about this smoothed frequency trajectories. Instead of MCMC, we could also estimate the maximum posterior and its variance. I included a little latex note in rneher:fitness_model. I am not done with the note, though.

**Comment by trvrb** [comment]
Basic model is in place. Closing.
