### ISSUE TITLE
GISAID flu B lineages aren't fully parsed

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#104]
I just noticed about 1/3 if all human flu B sequences in GISAID are not assigned Vic or Yam. I noticed this because new B sequences from the global migration paper weren't getting included.

I think to correct for this we could use all B sequences in a pipeline (say for Vic), but then clean to keep only sequences similar enough to modern Vic HA.

**Comment by rneher** [comment]
Yes, this would probably be a good idea. basically in the script that adds new sequences put in an extra alignment step a recent B sequence from each lineage.

**Comment by trvrb** [comment]
Fixed in #106.
