### ISSUE TITLE
Fix frequency labels

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#127]
Labels on frequency plots are off by 1 month.

**Comment by trvrb** [comment]
The labels appear correct. Frequencies go through:

```
    2016.0, 
    2016.0833333333333, 
    2016.1666666666667
```

And the plot shows:

![h3n2_mutations_panel](https://cloud.githubusercontent.com/assets/1176109/13128198/f502804c-d588-11e5-9cb8-be269e678f00.png)

The final three points are Jan 1, Feb 1 and March 1, respectively.

Perhaps it is confusing to have the final timepoint in the future. Two options:
1. Switch final timepoint to the date that the analysis is run. Seems annoying to implement.
2. Drop current final timepoint. Report up to Feb 1.

**Comment by rneher** [comment]
yeah, technically correct but a little confusing. just doing 2014, 2014.5 etc might be less ambiguous
