### ISSUE TITLE
Strain vs clade fitnesses

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#13]
I think I may have an idea about why optimizing the current fitness model is doing little to improve clade frequency projections. This issue is based on commit a162c9f4222089539fb543e36c8f936e5411df47.

Here, I calculate mean absolute error in clade frequency estimates from season _j_ to season _j_ + 1. With _&beta;_ set to 0 for all 3 predictors. The mean absolute error starts out at 0.227. This seems reasonable for a null model. However, running `learn_parameters` only drops this to 0.217. There seems to be very little predictive power in the current setup.

Currently, each clade is is given a frequency in season _j_ and _j_ + 1, and also a triplet of standardized predictors that goes into `model_fit_by_season`. This looks something like:

```
freq: [[ 0.21453287  0.20496894]
 [ 0.39100346  0.20496894]
 [ 0.11072664  0.13664596]
 [ 0.11764706  0.17391304]
 [ 0.14186851  0.        ]
 [ 0.74048443  0.40993789]
 [ 0.25259516  0.58385093]
 [ 0.25605536  0.58385093]
 [ 0.25951557  0.58385093]]
pred: [[ 2.66041486 -1.4753209  -0.15705363]
 [ 3.7866957  -0.17937032 -0.15705363]
 [ 2.2088845   1.11658026 -0.15705363]
 [ 0.69428397  1.11658026 -1.2126001 ]
 [ 1.34898559 -0.17937032 -2.26814657]
 [ 2.81380694 -0.17937032 -1.2126001 ]
 [ 2.2163995  -0.17937032 -0.15705363]
 [ 0.59322631 -0.17937032 -0.15705363]
 [ 0.12137165 -0.17937032 -1.2126001 ]]
```

Clade frequencies in season _j_ + 1 are predicted by

```
freq[:,0]*np.exp(self.fitness(params, pred))
```

so based only on the clade itself. However, in L&L eq 1:

![temp](https://cloud.githubusercontent.com/assets/1176109/6012326/9d79ce38-aafb-11e4-9eda-4bd1134a38ef.png)

clade frequencies derive from summing virus frequencies for viruses that subtend a clade, so only viruses get assigned fitnesses and clade frequencies just track virus dynamics.

**Comment by trvrb** [comment]
I've implemented the eq 1 approach in 934046aaa2bd47b9943e91ec92db81662f3a96d4. With `predict` I get the following for my test dataset:

```
initial function value: 0.235712900237
final function value: 0.225196567475
fit parameters:
offset: 0.12877991281
lb : 0.00123525550776
ep : 0.0407099061651
ne : -0.0677790859936
```

With the new `predict_tree` function, I get:

```
initial function value: 0.222965116057
final function value: 0.126603031826
fit parameters:
lb : 0.419621449144
ep : 1.62831337906
ne : -0.879101664485
```

Definite improvement. All the signs are in the expected direction and as expected `ep` is the most predictive parameter. Note that I normalize strain frequencies based on all the strains from a season, so the `offset` parameter is no longer needed.

The current `model_fit_tree` is far from optimized, but what do you think of the basic approach?

**Comment by rneher** [comment]
I am surprised this makes this big a difference. at least for smaller clades I would have expected that they are pretty homogeneous and globbing strains together is ok. I can work on speeding this up.

**Comment by rneher** [comment]
it also seems rather unconstrained. I just ran it on the 10y_50v tree and got this:
fit parameters:
lb : 1.37877417844
ep : 2.36501325829
ne : 1.12224508817

**Comment by rneher** [comment]
comparing different subsets of predictors compared to the initial value: 0.23
all three predictors: 0.13
lbi only: 0.16
ep only: 0.18
ne only: 0.228 (i.e. very little)
ep and ne: 0.178
 strangely, the ne has a positive contribution.

**Comment by rneher** [comment]
much faster now, bottleneck is translating the sequences.

**Comment by trvrb** [comment]
> I am surprised this makes this big a difference. at least for smaller clades I would have expected that they are pretty homogeneous and globbing strains together is ok. I can work on speeding this up.

From looking at things, I think most of the improvement was in normalization of total predicted strain frequencies in season _j_ + 1 to 1. I think the `offset` parameter really wanted to vary from year to year. This takes care of that.

**Comment by rneher** [comment]
yes, this is plausible

**Comment by trvrb** [comment]
### Parameter fits

For `tree_refine_10y_5v.json`:

| Parameter | Fit | Frequency error |
| --- | --- | --- |
| lb | 0.54 | 0.21 |
| ep | 1.51 | 0.15 |
| ne | 0.33 | 0.22 |
| lb, ep | 0.65, 2.31 | 0.13 |
| lb, ne | 0.50, 0.26 | 0.21 |
| ep, ne | 1.41, -0.29 | 0.14 |
| lb, ep, ne | 0.42, 1.63, -0.88 | 0.13 |

For `tree_refine_10y_50v.json`:

| Parameter | Fit | Frequency error |
| --- | --- | --- |
| lb | 1.17 | 0.16 |
| ep | 1.86 | 0.18 |
| ne | 0.09 | 0.23 |
| lb, ep | 0.93, 1.10 | 0.18 |
| lb, ne | 1.37, 0.64 | 0.15 |
| ep, ne | 1.85, 0.19 | 0.18 |
| lb, ep, ne | 1.38, 2.37, 1.12 | 0.13 |

**Comment by rneher** [comment]
yes, I got the same values (for 50v at least, didn't do the other one). not quite clear how to interpret ne>0.

**Comment by trvrb** [comment]
For `10y_5v` ne doesn't add basically anything on it's own and doesn't add anything when matched with other parameters.

I don't understand lb+ep for `10y_50v`. It's lower than setting ep to 0. Must mean some difficulty in optimizing the function?

**Comment by rneher** [comment]
yes, starting with [1,0] gives:
final function value: 0.162664442388
fit parameters:
lb : 1.16806640625
ep : 4.8583984375e-05

**Comment by trvrb** [comment]
In L&L they don't fit the non-epitope parameter and instead fix it a priori. I suspect that might have been for similar reasons.

@mluksza --- do these results make sense to you?

**Comment by rneher** [comment]
I just added a loop that tries a bunch of random initial values and picks the best.

**Comment by mluksza** [comment]
estimation of sigma_ne is unstable, and in my experience it was overfitting to particular years. Setting it globally is giving positive information gain on the test set for me. You also have to be careful when you classify mutations as deleterious, it appears to me that in your _50v tree you may have classified mutations that are in fact neutral and this component starts acting as a weak branching-like component (rewarding branching events associated with those mutations). Do you count ne from the LCA or from a*?

**Comment by rneher** [comment]
@mluksza what do you mean by a*

**Comment by trvrb** [comment]
It's eq 17 of the L&L paper, so that **a**\* is the "sequence of its closest ancestor from a previous season". I'm still a bit hazy on its concrete implementation however.

**Comment by rneher** [comment]
yes, I remember this bit. this basically rewards short terminal branches.

**Comment by trvrb** [comment]
@mluksza ---

So, let's say we have season _j_ that is viruses from the current year. We're trying to predict clade frequencies in season _j_ + 1. In this case, non-epitope distance is the distance from a virus **a**_i to the closest ancestor in season _j_ - 1? This closest ancestor is the most recent common ancestor of tips from season _j_ -1 and season _j_?

**Comment by mluksza** [comment]
Right, it is a_i\* to be exact, that is for each strain i from season t, you find the closest ancestor from season t-1
ne mutations that survived one or more seasons are reclassified as neutral

**Comment by mluksza** [comment]
take the path from strain i to the root. a_i\* is the first node on this path assigned to season t-1.

**Comment by mluksza** [comment]
you have to assign internal nodes to seasons. I simply assign each internal node to the season of the oldest daughter

**Comment by trvrb** [comment]
So, concrete example:

![photo](https://cloud.githubusercontent.com/assets/1176109/6028347/aa053230-ab9d-11e4-8612-35adeb742d7c.jpg)

Tips A, B and C are from season _t_ and tips D, E, and F are from season _t_ - 1. In computing non-epitope distances, you would compare:

Tip A to internal node X
Tip B to internal node X
Tip C to internal node Y

?

**Comment by mluksza** [comment]
yes!

**Comment by rneher** [comment]
would be easy to put this into the current scheme. dendropy trees are doubly linked. hence you simply walk back until hit a clade that is in the desired season (i.e. has .len(.tips[t-1])>0)

**Comment by trvrb** [comment]
Great! So let's make a `ne_star` (or something) predictor to compare against.

**Comment by rneher** [comment]
I pust pushed a first pass at it. Sometimes the optimization runs off to very large parameters which will results in tremendously large fitness variation and basically a winner takes all model. this is probably not what we want, even though it has a small error by our metric.

**Comment by trvrb** [comment]
Excellent! I'm making a couple more small changes to `fitness_model` and then I'll merge this branch with `master`.

**Comment by rneher** [comment]
I reinstantiated a check that a clade we used for fitting isn't just a trivial parent of the same daugther clade (when restricted to a particular season)

**Comment by rneher** [comment]
the fact that the coefficients sometimes run off bothers me a bit. it means that some times the smallest error is achieved by predicting 0/1 frequencies to clades, which I guess is a sign of overfitting (using three of four parameters to pick as many winning clades in 10 years as possible)

**Comment by trvrb** [comment]
I just pushed a command line parser for predictor names. Makes comparing individual predictors much easier.

**Comment by rneher** [comment]
I added the mutational tolerance. does not do so badly!
