### ISSUE TITLE
Recalculating global clade frequencies before running the prediction pipeline improves the clade error

### ISSUE THREAD

**Issue by huddlej** [blab/nextflu#143]
The frequencies are actually the same before and after recalculating, but the `clade_fit` method depends on the values of the `tips` attribute of each node. This attribute is overwritten during each iteration of the "frequencies" step in the pipeline, so the values in the `tips` attribute at the end of the augur pipeline belong to the last region that was assessed (e.g., Oceanic).

The prediction pipeline expects the `tips` to refer to the global frequencies, though, so when `clade_fit` uses this attribute to predict the final frequency of each clade, it's only using the tips associated with the Oceanic region. When I force the global frequencies to be recalculated, `node.tips` gets overwritten again with the global region's results and the prediction pipeline works as expected.

Node tips get overwritten in the estimate_tree_frequencies method: https://github.com/blab/nextflu/blob/7195646bd4e0acff2ec4f0c355a8f2d81b4dc88d/augur/src/bernoulli_frequency.py#L438

Those tips get used in clade_fit here:
https://github.com/blab/nextflu/blob/7195646bd4e0acff2ec4f0c355a8f2d81b4dc88d/augur/src/fitness_model.py#L223-L224

**Comment by trvrb** [comment]
Closing in favor of moving development to [nextstrain/augur](https://github.com/nextstrain/augur).
