### ISSUE TITLE
Include frequency panel

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#17]
Add frequency panel below tree in auspice. Each node in JSON will be annotated with a pivot list. Take these pivots and interpolate with D3. Mouseovers of branches of the tree would update the frequency panel.

**Comment by rneher** [comment]
I pushed a version into mutation_frequencies that produces jsons with clade and mutation frequencies (should show up in your dropbox). could you put a geo annotated 3y json into the dropbox? this way I don't have to run the tree building etc.

**Comment by rneher** [comment]
the frequency estimation is now done for all subclades larger than a certain threshold. subclade frequency estimate partition the clades and are then multiplied by the frequency of the parent clade to provide consistent subfrequency estimates. Each node carries a vector of frequencies (both regular and logit, the latter being sometimes better for interpolation). In addition, mutation and canonical clade frequencies are produced and saved as json. what is still missing is doing frequency estimation separately for geographic regions, but it is a simple matter of filtering the observations.

**Comment by rneher** [comment]
I added smth that calculated the frequencies of all genotypes. I also played with some very simple plotting in auspice. (it doesn't work on my machine due to these CORS issues, but I figure there is a plotting library that you like to use and I won't invest too much time...) I suggested a format for region:genotype specification, take a look at 1f8374e9fba3312189170bd1fd1d0d0e7a733ae4

**Comment by rneher** [comment]
I added c3 to make charts. works nicely. to make it work, copy the genotype_frequency.json (in dropbox) into auspice/data

**Comment by rneher** [comment]
I added a preliminary panel that shows frequencies of clades on mouseover. This adds quite a bit of overhead, but it is not too bad as to be annoying. it needs the tree_frequencies.json (in drobbox). we also need to work on the layout/adding legends/explanations....

**Comment by trvrb** [comment]
This is fantastic progress! Thank you @rneher. I've been playing around with things in their current state and thinking about what we should aim for and I have the following suggestions. Please feel free to disregard or argue against.
- I feel like including geographic regions in the frequency plots is overwhelming. Especially because it's completely unclear whether differences across regions are real or sampling artifacts. Having these calculated across regions is awesome in that we can work toward a predictive model that does regional predictions, but I'm not sure it should be in auspice at this point.
- I might imagine a single input box for "paint tree" and "plot frequencies". The resulting genotype frequency lines would live in the same plot element as the clade frequency lines given on mouseover (not sure if best location is below or to the right). The same sites would be given frequency lines and would be used to color the tree.
- Feels like extra work to have to specify "159Y". Should just specify "159" and the plot will show all the variants at site 159.
- Struggling with how to incorporate clade designations (3C2, etc...). Maybe checkboxes? And when checked it would mark the tree and fill in the frequency plot?

**Comment by rneher** [comment]
- yes, region specific frequencies can be quite noisy and there is probably too much info (shaky) here at the moment, but for big clades and individual mutations, it should be ok. We could make the global line fat and the others faint
-  right now, the input boxes operate in a slighly different mode. one does all genotype combination at the these positions but without region specificity, the other allows for region specific mutations and genotypes. I am not sure what people want (maybe ask Colin).
- regarding clades, we could have uses simply enter them into the box and check whether this field is part of the json. we need an explanation of what to input anyway.

**Comment by rneher** [comment]
regarding legend: we could put it above the clade frequency panel. Some explanation of features could be in the lower left. but I have little intuition for aestethics and layout....

**Comment by rneher** [comment]
fiddled a little with a legend. kind of works, could use more explanations. I also removed the region specific freqs from the clade frequency panel and added a box with explanations. linking the mutations/genotype frequencies to the clade plot would be nice, but not obvious to me how to do w/o too much effort. the date slider and the genotype coloring behaves a little weird.

**Comment by trvrb** [comment]
Wow! This is starting to look really good. Some specific comments:

> yes, region specific frequencies can be quite noisy and there is probably too much info (shaky) here at the moment, but for big clades and individual mutations, it should be ok. We could make the global line fat and the others faint
> I also removed the region specific freqs from the clade frequency panel

I think it's great the option to plot region specific frequencies was maintained in the genotype frequency plot. My idea here to include the most functionality and not be overwhelming would be to add a select box to the bank on the left that says "Include viruses from" with options "everywhere", "North America", "Europe", etc...

This would cause only viruses from the selected region to show up on the tree and would also modify the clade-frequency mouseover appropriately. I think there's a lot of power in being able to compare tree to other readouts. The question would be "what's going on in Europe?" and this would be the answer. And the subset to East Asia would be particularly relevant.

> added a box with explanations...

This is awesome. It would be good to maintain a responsive design in whatever layout we end up with. But this shouldn't be too difficult with bootstrap columns.

**Comment by rneher** [comment]
looks like I broke the genotype frequencies when rounding (I tried to force rounding by string truncation to avoid 0.2000000000002 type output, but it is prone to problems)

**Comment by rneher** [comment]
I am rerunning the frequency estimation now. will take an hour or so, after which the new jsons should be in dropbox. feel free to play with the layout, explanations, or change the behavior of stuff. I won't touch it.

**Comment by rneher** [comment]
The new files should be in dropbox, all seems to work for me. I guess before we close this, we should
- include the frequency part into the processing pipeline
- remove the aa_seq pruning (otherwise auspice will break for genotype coloring)
- polish the interface.

**Comment by trvrb** [comment]
I believe this is closed as of 4ed1914db1b964b21606f7c0b9b7aafe0079d60c. Layout needs some improvement, but this is a separate issue (#29).
