### ISSUE TITLE
Include color legend

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#19]
There should be a legend on the left hand side that orients colors. It's been completely non-obvious to people I've showed this to that red is high, green is medium and blue is low.

**Comment by rneher** [comment]
we will need also a categrorical legend for the genotypes and regions. I had smth like this in my version. maybe one can pick a few things from there.

**Comment by trvrb** [comment]
Great idea. I'll pull from your working version.

**Comment by rneher** [comment]
good. probably just looking for inspiration is good enough. some of the genotype collecting and coloring stuff might be useful too. tree_frequencies now adds the 10 most dynamics mutations to each node (somehting like this: node['gt'] = 'AFGHYSJFDT'). the root node has a field gt_pos = [3,45,67,159,234,...] with the corresponding positions in HA1 numbering.

**Comment by rneher** [comment]
I implemented a very rough genotype coloring, still missing a legend. it takes positions from an html input field, generates all genotypes, and colors the links leading up to them. needs beautification.

**Comment by trvrb** [comment]
I think this can be closed as of bea7a6110c345701067aa17dc590b570046ae015.
