### ISSUE TITLE
Trait clarification

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#21]
Via @colinarussell ---

> Local branching index will be foreign to most viewers, would be helpful to have a one sentence description/interpretation and a link to our eLife paper (or wherever else you think people should refer for information)

Also would be good to include links to papers detailing epitope / non-epitope designations.

**Comment by rneher** [comment]
how many words be can spend here depends a little on the layout. I can include links to LBI -> eLife and epitope -> L&L

**Comment by trvrb** [comment]
Okay. I'll try to get the layout in place first thing.

**Comment by rneher** [comment]
I added a longer explanation of stuff at the bottom dd10809fb3a9c525fd9fbe4b33d1636e1e245219
feel free to edit the prose and cut/add as you feel

**Comment by rneher** [comment]
and close if you are happy.

**Comment by trvrb** [comment]
Fixed in #34.
