### ISSUE TITLE
Inference of region ancestry

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#22]
Looking at the region coloring, it's apparent that there are frequently smaller clades comprising viruses from only (or almost entirely) a single region. It would be useful to annotate internal nodes with inferred region affiliations. A simple approach to this would be to reuse @rneher's ancestral reconstruction code with a 10x10 transition matrix with uniform entries (equivalent of Jukes-Cantor). Zero length branches would need to be given some small delta. Internal nodes with zero-length branches to multiple viruses from multiple regions should end up being assigned the region of their predominate strains.

Not high priority.

**Comment by rneher** [comment]
using the ancestral reconstruction should be easy. one can specify the attribute name to something other than seq, we could input the location as a fake alignment of length 1 with 10 letters corresponding to regions. A minimal branch length is already in place, but we might just specify a different branch length attribute and assign it some combination of difference in sampling data and genetic distance + a few days. The main question is whether we want to generalize the existing, or copy and specialize. Generalize and subclass would be the more elegent way

**Comment by trvrb** [comment]
This is also slated for augur v2. Won't make it to the v1 codebase.
