### ISSUE TITLE
Region-specific display

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#23]
Should add a select box that limits displayed viruses to those from a single region. Clade frequency plots should also update accordingly.

**Comment by trvrb** [comment]
Via @rneher ---

> regarding the region switch, I think that would be a great idea. Checkboxes that selected tips from certain regions (make everything else grey) and restrict the clade frequency panel to that region (we could do any combination like Europe+NorthAmerica and simply do a weighted average of the frequencies. we might also want to plot the isolates/month.

I like the idea of being able to select multiple regions, but I don't like the idea of cluttering the IO panel with 10 different checkboxes. Not sure what the best solution is here.

**Comment by rneher** [comment]
yes, ten check boxes would be messy. we could work with coarser regions, but then the combining is not longer that interesting. We could select super-regions from a pull-down menu and then added 3-5 subregions to select and combine.
