### ISSUE TITLE
Mouse over clarification

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#25]
Via @colinarussell ---

>  I think it would help users to clearly discuss "branches" and "tips" in the feature explanation so that they know to mouse over branches to get the clade frequencies. This can be done very simply - "pull down menu: decorate _branch tips_ with the number mutations relative to root" vs "mouse over a branch _(not tips)_ to display the /clade frequency/ on the right” (the italics are a suggestion for change).

**Comment by rneher** [comment]
would be great if clades changed in appearance slightly when mouse-overed. like glowing or smth.... but save for later.

**Comment by trvrb** [comment]
Yes! Absolutely. Virus tips could use the same behavior as well. And the same size / glow could be used to help identify strains via strain search box.

**Comment by trvrb** [comment]
Fixed in #34.
