### ISSUE TITLE
Genotype frequency input box clarification

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#27]
Via @colinarussell ---

> It would help casual users to include slightly more specific instructions for use - examples:
> 
> "colour tree by HA1 positions: specify positions to color the tree by genotype. Amino acid positions must be separated by a comma (e.g. 159,225).”
> 
> "Mutation and genotype frequencies: specify genotypes to graph frequency through time. For example, 159Y/159S will plot frequencies of viruses with 159Y and 159S. Substitutions must be separated by /. Optionally, frequencies can also be plotted by region. For example, NA:159Y/NA:159S will plot frequencies of 159Y and 159S in North America. Currently, region plots are only available for Asia (AS), North America (NA), Europe (EU), and Oceania (OC). Beware that regions specific frequencies are noisy.”

**Comment by trvrb** [comment]
I was actually finding the `,` and `/` parsing quite non-intuitive. I keep expecting the opposite behavior, i.e. `159Y/225D, 159S/225D` to plot a line for 159Y+225D and another line for 159S/225D.

Is the current parsing somehow standard?

Also possible, would be: `159Y/225D/EU, 159S/225D/NA` to specify regions. Eliminates the confusion with `:` vs `/` vs `,`.

What do you think?

**Comment by rneher** [comment]
anything that can be readily parsed and is intuitive works for me. It should be consistent with the genotype coloring though. there we currently specify positions separated by comma and genotype at all of these positions matters. But your choice.

**Comment by trvrb** [comment]
I see. Do you think that specifying `159, 225` as genotype coloring is consistent with specifying `159Y/225D, 159S/225D` as genotype frequency?

I feel like it is, as the simple input would be `159Y, 159S, 225D`, i.e. plot these different things.

I think that it should be okay for the following to mean exactly the same thing:

```
159Y/225D/EU, 159S/225D/NA
159Y 225D EU, 159S 225D NA
```

Commas are the only thing that matters for separating elements. Anything that's not a number or a letter or a comma can be used to separate attributes.

**Comment by rneher** [comment]
sure, that would work. I don't have any real preference. you only need to pull out the region.

**Comment by rneher** [comment]
I changed the parsing. 1554449a28ec025638d534c712c567888680b913

I am not terribly familiar with regex. the current thing works, but is a little restricted. I am sure you can make it more robust with 5 characters of regex wizardy line 986 in auspice

**Comment by trvrb** [comment]
Fixed in #34.
