### ISSUE TITLE
Auspice loading speed

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#28]
Should refactor to remove amino acid sequences from main `tree.json` file. Load new `sequences.json` after `tree.json` and link between files via clade ids. (Need to restore clade ids in `tree_streamline.py`).

**Comment by trvrb** [comment]
Can further improve by moving `logit_freq` lists out of `tree.json` and into `frequencies.json`. Still linking between files with clade ids.

**Comment by rneher** [comment]
we could in principle separate tree, sequences, and frequencies if we have a consistent labeling.

**Comment by trvrb** [comment]
Yes! Exactly.

**Comment by trvrb** [comment]
Still need to separate clade frequencies, but I'm going to pull this into `master` and keep the issue open.

**Comment by rneher** [comment]
zipping would probably be the biggest improvment:

 483K Apr  5 08:28 H1N1_frequencies.json
 7.3K Apr  5 08:28 H1N1_meta.json
 277K Apr  5 10:08 H1N1pdm_frequencies.json
 4.2K Apr  5 10:08 H1N1pdm_meta.json
 1.5M Apr  5 10:08 H1N1pdm_sequences.json
 1.1M Apr  5 10:08 H1N1pdm_tree.json
 553K Apr  5 08:28 H1N1_sequences.json
 680K Apr  5 08:28 H1N1_tree.json
 281K Apr  5 08:28 H3N2_frequencies.json
 2.2K Apr  5 08:28 H3N2_meta.json
 1.3M Apr  5 08:28 H3N2_sequences.json
 898K Apr  5 08:28 H3N2_tree.json
 169K Apr  5 09:53 Vic_frequencies.json
 4.2K Apr  5 09:53 Vic_meta.json
 1.4M Apr  5 09:53 Vic_sequences.json
 959K Apr  5 09:53 Vic_tree.json
 208K Apr  5 09:57 Yam_frequencies.json
 4.2K Apr  5 09:57 Yam_meta.json
 1.1M Apr  5 09:57 Yam_sequences.json
 775K Apr  5 09:57 Yam_tree.json
/auspice/data$ gzip *json
/auspice/data$ ls
  27K Apr  5 08:28 H1N1_frequencies.json.gz
 1.2K Apr  5 08:28 H1N1_meta.json.gz
  20K Apr  5 10:08 H1N1pdm_frequencies.json.gz
  915 Apr  5 10:08 H1N1pdm_meta.json.gz
  19K Apr  5 10:08 H1N1pdm_sequences.json.gz
 120K Apr  5 10:08 H1N1pdm_tree.json.gz
 8.6K Apr  5 08:28 H1N1_sequences.json.gz
  67K Apr  5 08:28 H1N1_tree.json.gz
  23K Apr  5 08:28 H3N2_frequencies.json.gz
  609 Apr  5 08:28 H3N2_meta.json.gz
  15K Apr  5 08:28 H3N2_sequences.json.gz
  97K Apr  5 08:28 H3N2_tree.json.gz
  13K Apr  5 09:53 Vic_frequencies.json.gz
  952 Apr  5 09:53 Vic_meta.json.gz
  16K Apr  5 09:53 Vic_sequences.json.gz
 105K Apr  5 09:53 Vic_tree.json.gz
  16K Apr  5 09:57 Yam_frequencies.json.gz
  886 Apr  5 09:57 Yam_meta.json.gz
  12K Apr  5 09:57 Yam_sequences.json.gz
  85K Apr  5 09:57 Yam_tree.json.gz

trees 10x, sequences 100x compression, frequencies 50x

**Comment by trvrb** [comment]
I have `s3_website` set up to automatically gzip `.html`, `.css` and `.js`. I just confirmed this is working as it should. `d3.min.js` is 143K locally and 50K on S3. JSONs are indeed a problem though.

**Comment by trvrb** [comment]
> zipping would probably be the biggest improvment

Looks like we'd have to code this ourselves for JSON files: http://stackoverflow.com/questions/294297/javascript-implementation-of-gzip Not so fun.

**Comment by rneher** [comment]
yeah, doesn't seem right.

**Comment by trvrb** [comment]
Wait... Maybe it's possible: http://stackoverflow.com/questions/8350749/gzipped-json-file-not-decompressing. I'll keep looking.

**Comment by rneher** [comment]
stumbled upon a number of these links earlier. I think with jquery and ajax, it's straight forward.

**Comment by trvrb** [comment]
This has been resolved in 3f2a4c38ac42f6756266ab3fcc6edfd9159e273a.
