### ISSUE TITLE
Explanation of features via screen shots?

### ISSUE THREAD

**Issue by rneher** [blab/nextflu#33]
Hi Trevor, just wondered whether we would help people by doing smth like this:
![epitope](https://cloud.githubusercontent.com/assets/8379168/6316025/6df1d3e4-ba15-11e4-90b4-1d84599fd7ae.png)

**Comment by rneher** [comment]
for the genotype coloring mouse over stuff, etc it might be more helpful then the example above...

**Comment by rneher** [comment]
could make a page with such screen shots and then link to it from the Feature explanation section.

**Comment by trvrb** [comment]
Nice idea. The simplest immediate thing would be to create a series of PNG screenshots that could be linked from the Feature Explanations.

**Comment by trvrb** [comment]
And a "Help" page could follow.

**Comment by rneher** [comment]
Well, lets just make a help page with different anchors (one per feature). we could use svg instead of PNG, that makes them editable.

**Comment by trvrb** [comment]
Perfect!

**Comment by rneher** [comment]
Great. I'll make those this afternoon (16h+ pacific)

**Comment by trvrb** [comment]
This is fixed.
