### ISSUE TITLE
Extrapolation of frequencies

### ISSUE THREAD

**Issue by rneher** [blab/nextflu#35]
a more sophisticated/consistent extrapolation could be tied in with the fitness model.

**Comment by trvrb** [comment]
As a first check, I'd wonder about using clade growth rate estimated from interpolation as a direct prediction of clade frequency a year out. How does this do compared to the current fitness model?

**Comment by rneher** [comment]
with a much rougher interpolation and the "winner-takes-all" measure we used in elife, growth rate was predictive but worse than the LBI. Our rational back then was that actual frequencies get perturbed by sampling issues and geostructure, to which the lbi is not very sensitive. But I wouldn't be surprised if with the bigger data set, better sampling etc frequency extrapolation does better.

**Comment by trvrb** [comment]
We have roughtly this in current fitness model code.
