### ISSUE TITLE
Refactor and clean up

### ISSUE THREAD

**Issue by rneher** [blab/nextflu#39]
I suggest we take a crack at making a few things more transparent

auspice: this is a bit of mess with declaration, variable definitions, and code intermingled. it would help if we made clear sections for say coloring, date slider stuff etc. A uniform way to deal with HA and HA1 positions would be good.

c3 charts: use json instead of column? http://c3js.org/samples/data_json.html

augur: things like all_descendents and tip_descendents are in fact methods of drendropy nodes leaf_iter and postorder_node_iter.

flatten the frequency json: there is no good reason to have [clades], [mutations] and [genotypes] as separate dicts with the dict. genotypes could be made more compact by ommitting the dots and only reporting positions that are tracked. 

I am sure we'll find more

**Comment by rneher** [comment]
Separating H3 and HA1 specific parts from generic tree building/reconstruction/etc would be good. 
we could make a module flu, that is subclassed to H1 and H3 and which would take care of the specific cleaning and annotation issues. similar things could then be done for other viruses

**Comment by rneher** [comment]
mostly done:
- config file now specifies a coding region. only this is translated and all amino acid positions are counted from the beginning of this sequence
-  all_descendents and tip_descendents are actually needed to transverse the json. could of course do everything necessary on the tree before converting to json, but that is ok
- frequency json can only be flattened when genotypes are dealt with differently
- c3 chart ticks are no longer static
- we now have a pipeline that can be subclassed and allows passing along/inspecting the intermediate results, configurable via a config file

**Comment by trvrb** [comment]
Major progress on this with #50. Not sure if this issue should be closed now or left open.

**Comment by rneher** [comment]
I think we can close this and open new ones if we feel like.
