### ISSUE TITLE
Cloudfront invalidation bug

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#42]
For some reason `index.html` is not being invalidated properly by Cloudfront after pushing to S3. This is causing the old `index.html` to be loaded, despite other files being updated.

Needs fixing today.

**Comment by rneher** [comment]
I get the latest index.html on nextflu.org. will go to the computer pool at KITP and try a a "virgin" browser.

**Comment by trvrb** [comment]
I think it's that Cloudfront is still sometimes serving old versions of `index.html` rather than browser caching. But I'm not 100% sure. You may be getting a different server than I am.

**Comment by trvrb** [comment]
Hmm... okay. I may have been confused. I think it was just my browser remembering the old `index.html`. Just did some tests. I think we're good.

**Comment by rneher** [comment]
It might have to do with some sync within amazon. my first access was via a vpn tunnel to europe, and that worked. at KITP, I first got an old version, but then upon reload I was ok. 
it works fine on an ancient mac/firefox, but tree doesn't show on ancient safari.

**Comment by rneher** [comment]
chrome on ancient mac works, but is super slow (as is everything else, chrome says hardware no longer supported).

**Comment by trvrb** [comment]
Calling this fixed.
