### ISSUE TITLE
Clade frequency mouse over is broken

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#45]
Not sure when this arose, but clade frequencies are no longer showing on mouseover.

**Comment by rneher** [comment]
it says "Error: Source data is missing a component at (0,1)!" I have had this before. did the json change?

**Comment by trvrb** [comment]
That's probably it. I reran the pipeline yesterday and pushed the updated json.

**Comment by trvrb** [comment]
But I think this means the current pipeline in `master` is producing incomplete json.

**Comment by rneher** [comment]
bernoulli_freqeuncies.py writes into genotype_frequencies.json, auspice loads frequencies.json could that be the issue?

**Comment by rneher** [comment]
the problem is that the tree doesn't contain a field 'pivots'. this should be a property of the root node. but it isn't. tree_util writes it, if it is there and should call the debugger if it fails.

**Comment by trvrb** [comment]
Thanks. I'll look into this tomorrow.

**Comment by rneher** [comment]
the first thing to check would be whether tree_frequencies.json has the "pivots" at the root node. If it does, the field got lost in streamlining.

**Comment by rneher** [comment]
should be fixed now. json export was broken by mishandling the virus_count field.

**Comment by trvrb** [comment]
Fixed by @rneher in c762dfe19f380fe69e4ddcf808961d16391f2b14.
