### ISSUE TITLE
Objects and serialization

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#47]
I had thought that original dict / json setup for `viruses` and `tree` offered a simple and light-weight approach. However, after our conservation this morning and thinking about things today I'm definitely realizing where you're coming from, particular for trees. At the moment, the RAxML newick is converted to dendropy, refined and then exported to dict / json, then loaded and converted to a biopython tree for ancestral state reconstruction then exported to dict / json, then loaded and converted to a dendropy tree for frequency estimation, and finally exported to dict / json for auspice. Having the tree as a dendropy tree / pickle won't solve all the conversations, but would reduce the amount of back and forth.

What about making a `tree` class that subclasses `dendropy.dataobject.tree.Tree`? And add convenience methods for IO, like the `dendropy_to_json` method we've been using. Computations on trees would still live in `tree_refine`, etc... Seems conceptually satisfying. Relevant methods in `process` would return `tree` objects.

**Comment by rneher** [comment]
I just pushed a new branch refactor

I switched ancestral over to dendropy and implemented pretty much all we talked about yesterday. still needs comments etc. working on the frequency estimation now.

**Comment by trvrb** [comment]
This is closed with #50.
