### ISSUE TITLE
Include larger HI dataset as source-data

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#48]
I had compiled a larger list of H3 antigenic data for the eLife paper. This should be included as source data.

**Comment by trvrb** [comment]
@rneher ---

I didn't have your more recent HI measurements on hand. Could you merge this data table with what you have?

**Comment by rneher** [comment]
Yes, will do. I have a whole bunch of tables as csv. I'll flatten them and include

**Comment by rneher** [comment]
still need to curate and stratify by ferret inocculated with the same virus

**Comment by rneher** [comment]
bigger data set + all NIMR tables since 2011 should in the flat file.
