### ISSUE TITLE
Include HI titer display in auspice

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#49]
It should be possible to just color raw titers relative to a selected reference virus. Can also include inferred titers for other viruses.

**Comment by rneher** [comment]
I have already added "serum" and "HI_info" flags to each node. could simply code the measurements into the tree by adding a {clade:titer, ...} dictionary to each node that corrresponds to a serum.

**Comment by rneher** [comment]
progress toward this in 4ab665a2e41009456ad781859aa05e3e34339caa

**Comment by trvrb** [comment]
More amazing progress. I think this is a great way to do things. The `HI_titers` branch is getting quite far along. Maybe we should think about merging it into `master`, but then stripping the `cHI` display option from `master` until we're completely happy.

**Comment by rneher** [comment]
I have been continously merging master into it, so it shouldn't be too diverged.

**Comment by trvrb** [comment]
Also worth thinking about. This same display would work if antigenic distance was taken from a map rather than directly from titers. Could still interpolate viruses with just genetic data.

**Comment by trvrb** [comment]
> I have been continously merging master into it, so it shouldn't be too diverged.

Ahh. Perhaps this is the most idiomatic way to handle this in Git. And merge into `master` only when the feature branch is completed. Thanks.

**Comment by trvrb** [comment]
Commit 4ab665a2e41009456ad781859aa05e3e34339caa has been pushed to http://dev.nextflu.org/

**Comment by rneher** [comment]
It doesn't seem to have updated the index.html? at least not for me.

**Comment by rneher** [comment]
loading via vpn from europe is ok....

**Comment by trvrb** [comment]
> It doesn't seem to have updated the index.html? at least not for me.

I figured out that this an issue with s3_website rather than CloudFront. s3_website does not properly invalidate the base `index.html` document. I have to go into AWS and invalidate it myself. The site http://nextflu-dev.s3-website-us-east-1.amazonaws.com/ should not have this issue (this is a direct look at the S3 bucket).

**Comment by rneher** [comment]
ok, that makes sense. anyway, it is amazing that this stuff works so well...

**Comment by trvrb** [comment]
I'm thrilled with AWS. Super cheap and super fast.
