### ISSUE TITLE
Make auspice selections RESTful 

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#52]
Should be able to pass in basic auspice selections (epitope vs non-epitope vs geography, etc...) through the URL. This would make sharing particular views of the data much easier.

**Comment by trvrb** [comment]
Looking into this now, this is more work than I expected. Parameters can be gathered from the URL using javascript with:

https://css-tricks.com/snippets/javascript/get-url-variables/

``` js
function getQueryVariable(variable) {
    var query = window.location.search.substring(1);
    var vars = query.split("&");
    for (var i=0;i<vars.length; i++) {
        var pair = vars[i].split("=");
        if (pair[0] == variable) {
            return pair[1];
        }
    }
    return(false);
}
```

And parameters can be moved to the URL with

http://stackoverflow.com/questions/3338642/updating-address-bar-with-new-url-without-hash-or-reloading-the-page

``` js
window.history.pushState("object or string", "Title", "/new-url");
```

However, this only works in modern browsers. Though another option is to use anchor URLS (hashes).

Hmmm, there is a bit of manual manipulation that would be required here. Hashes would be:

```
nextflu.org/#ep
nextflu.org/#ne
```

etc... Might be the easiest option.

**Comment by trvrb** [comment]
Actually, take a look at how this works:

http://earth.nullschool.net/#current/wind/surface/level/orthographic=-155.80,11.73,292

Hashed string stores all the info needed.

**Comment by rneher** [comment]
Yes, this would be quite useful. we should set all the menus and sliders to correct position though.

**Comment by trvrb** [comment]
This slated for auspice v2. Won't make it to the nextflu/auspice codebase.
