### ISSUE TITLE
strain search displays tips in the wrong place

### ISSUE THREAD

**Issue by rneher** [blab/nextflu#56]
when I search a strain, the tooltip shows up in the top left corner, regardless of where in the tree the strain is located.

**Comment by rneher** [comment]
do you observe the same behavior? sort of nullifies the search for me...

**Comment by trvrb** [comment]
I'm not getting this behavior with Chrome on Mac. Tooltip shows up in the same place for search and mouse over.

**Comment by trvrb** [comment]
But Mac Firefox gives the broken behavior. Mac Safari works fine.

**Comment by rneher** [comment]
chrome on linux works fine

**Comment by trvrb** [comment]
I'm no longer getting this bug on Mac Firefox. Closing.
