### ISSUE TITLE
Include mutation labels

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#58]
Include calculation of branch-specific AA changes in HA1 numbering in augur. And then show these changes on mouse-over in auspice.

**Comment by rneher** [comment]
I felt like a little programming (after chasing other peoples bugs all day...)

c8d371ef3ef7f0145c558ba81a6086166e6f0532

**Comment by rneher** [comment]
piggy-backed 85710748b2a069c227c316065147f35c7eda342a onto this branch. Colin had suggested such labels.

**Comment by rneher** [comment]
closed with f86ac0bdefd8aeb1c9254ee1868b59ceb78ab2a0
