### ISSUE TITLE
Geography

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#7]
- [x] Parse geographic information from strain names and include `geo` field in JSON.
- [x] Color viruses in auspice based on geography.

**Comment by trvrb** [comment]
Parsing is complete. Now need to display in auspice.

**Comment by trvrb** [comment]
@rneher ---

I pushed this change to the live site. You can see a subtle, but I think definite, effect where hotter viruses from China, India and Southeast Asia tend to be farther along than colder viruses from Africa and South America.

**Comment by rneher** [comment]
great!
