### ISSUE TITLE
JSON export occasionally fails

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#77]
JSON export in `process.py`, method `export_to_auspice` / `write_json`, still occasionally fails. Seemingly randomly, it will only export ~half the JSON file.

I'm not sure that this line is actually doing its job:

``` python
try:
    read_json(self.auspice_tree_fname)
except:
    print "Read failed, rewriting with indents" 
    write_json(self.tree_json, self.auspice_tree_fname, indent=1)
```

However, I _think_ but I'm not certain that this bug goes away when setting `indent = 1` or whatever instead of `None`. If this is indeed the case, a simple fix, while maintaining minified JSONs would be to export to auspice with `indent = 1`, but then have Jekyll minify the JSONs when compiling. There are plug-ins, like [`jekyll-press`](https://github.com/stereobooster/jekyll-press) that do basically this already.

**Comment by rneher** [comment]
it never happened for me... maybe some mac json lib is buggy

**Comment by trvrb** [comment]
Interesting that this hasn't been a problem for you. I thought that `indent = 1` might have been a solution, however, I'm getting the same occasional behavior. I'll continue to investigate.

**Comment by rneher** [comment]
do you get any error msg? one possible explanation could be a max_recursion problem. this can be set in sys

**Comment by trvrb** [comment]
It fails silently. I'll check out max_recursion.

**Comment by YuliaZhou** [comment]
This bug happened to me too.

**Comment by trvrb** [comment]
Thanks for letting us know @YuliaZhou.

**Comment by YuliaZhou** [comment]
Do you have the solutions?

**Comment by rneher** [comment]
@YuliaZhou we haven't encountered this problem in a long time and our best guess is that it is caused by the json lib (and in fact it always worked for me on linux).

**Comment by trvrb** [comment]
Hasn't been a problem for a while. Closing.
