### ISSUE TITLE
switch absolute/HA1 numbering

### ISSUE THREAD

**Issue by rneher** [blab/nextflu#79]

**Comment by rneher** [comment]
this would really be quite easy:
1) run pipe-line with --ATG
2) write branch mutations as (pos, ancestral, derived) tuples rather than string
3) include signal peptide length in as variable in H3N2.js etc
4) define an offset variable that is either -1 or signal_peptide-1 depending on checkbox
5) subtract this from the mutation position here: 
https://github.com/blab/nextflu/blob/master/auspice/js/auspice.js#L340 
6) add it here
https://github.com/blab/nextflu/blob/master/auspice/js/auspice.js#L1115
https://github.com/blab/nextflu/blob/master/auspice/js/auspice.js#L1273

legends would still need fixing.

**Comment by trvrb** [comment]
Closing in favor of position logic in [nextstrain/augur](https://github.com/nextstrain/augur).
