### ISSUE TITLE
Ancestral substitution model

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#8]
RAxML exports its inferred GTR parameters. Take these parameters and feed to `tree_ancestral`.

**Comment by rneher** [comment]
Yes, this would make sense. even though a site averaged substitution model is probably not much better than a flat one... I can look into parsing it, but I'll be pretty busy until Friday night.

**Comment by trvrb** [comment]
This is slated for inclusion in augur v2. Won't make it in here.
