### ISSUE TITLE
Alternative data resolutions

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#82]
I think folks want to be able to see all / almost all of their recent strains. I thought options like pasting in a FASTA and doing some client side match, but I don't think this will work well.

I'd propose running 3 pipelines for each of H3N2, H1N1pdm, Vic and Yam, one with `-y 1`, one with `-y 3` and one with `-y 6`. This would gives URLs like `nextflu.org/H3N2/1y/`. The URL `nextflu.org/H3N2/` would redirect to `nextflu.org/H3N2/3y/`, while `nextflu.org/Vic/` would redirect to `nextflu.org/Vic/6y/`. There'd be a `<select>` box to switch between resolutions. Probably under the virus select box.

In each case `-v` would be set to achieve the ~1500-1800 sequences we're currently targeting.

This would not be much coding, but would add considerable processing overhead. I'd like to get a dedicated box running the pipeline anyway however.

**Comment by rneher** [comment]
Yes, this is a reasonable idea. Alternatively, we could make the subsampling procedure "top heavy", i.e 100 in the first 12 month, 50 in the next 12 and 20 in the first 12. 

re processing: for the time being, I can run it on our cluster.

**Comment by trvrb** [comment]
> Alternatively, we could make the subsampling procedure "top heavy", i.e 100 in the first 12 month, 50 in the next 12 and 20 in the first 12.

We can certainly experiment with this. However, I am a bit concerned that this will make this year's clades _look_ like they're expanding just because of more samples.

**Comment by rneher** [comment]
yes, this is going to happen, (not in terms of frequency, but visual impression incl LBI).

**Comment by trvrb** [comment]
This has been implemented.
