### ISSUE TITLE
LBI scaling

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#85]
Should LBI be on a strictly relative scale, i.e. between 0 and 1? Other colorings (like `dfreq`) adjust the color scale so that the dynamic range of the colors are used, but the statistic still has an absolute underlying scale. Would it make sense to move LBI to a similar scheme?

**Comment by rneher** [comment]
I'll play with this a little. the absolute value depends on few things like the tau and the total number of nodes. but I agree in general it would be better to have this on an absolute scale

**Comment by trvrb** [comment]
(Mostly) resolved in 141296270a392c176d09f3cb0b2adca8cf586ba3.
